spring:
  profiles:
#    include: logging,redis,rds,storm,mail,web,actuator
    active: local

server:
  port: 8771  #web port for rest
  address: 0.0.0.0  #web server address
  contextPath: /application/rest/v1